version: '3'
services:
  app_almuerzo:
    build:
      context: .
    # ports:
      # - 3000:3000
      # - 3344:3344
    expose:
      - "3344"
      # - "3000"
    hostname: template
    restart: always
    environment:
      - TZ=America/Lima
      - VIRTUAL_HOST=cocina.apps.com.pe,www.cocina.apps.com.pe
      - LETSENCRYPT_HOST=cocina.apps.com.pe,www.cocina.apps.com.pe
      - LETSENCRYPT_EMAIL=miguekos1233@gmail.com
      - VIRTUAL_PORT=3344
      # - VIRTUAL_PORT=3000
    links:
      - mongodb
      - rabbitmq
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    command: pm2-runtime server.config.js --env production

  rabbitmq:
    build:
      dockerfile: rabbitMQ.DockerFile
      context: .
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/

  mongodb:
    image: mongo:latest
    restart: always
    hostname: mongo_alegra
    container_name: mongo_alegra
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changethis
    volumes:
      - /usr/local/volume/mongo:/data/db
    ports:
      - 27018:27017


networks:
  default:
    external:
      name: nginx-proxy_default